### ISSUE TITLE
It looks very nice

### ISSUE THREAD

**Issue by MacLeek** [OsciiArt/DeepAA#1]
Sorry, I can not understand Japanese language. I think your work looks promising :+1:  I've also written some codes trying to achieve the results as Xu did in her [article](http://www.cse.cuhk.edu.hk/~ttwong/papers/asciiart/asciiart.html), but what I got is pretty messy as in the following image(70 chars a line) :disappointed_relieved:
![image](https://cloud.githubusercontent.com/assets/3632691/23608681/7c8bb7be-02a5-11e7-86b9-e7429180c0ea.png)
Hope you can write an article explaining the details about how you train the model :grin:

**Comment by OsciiArt** [comment]
I thank you for your comment.
Yes, I plan to add the model training code and  the training data processing code in future, maybe in a week. please wait for a while

**Comment by Edward-liang** [comment]
本土に面白いですね。
このほか、何が実際の応用シーン はありますか。
圧縮できる方法は見られますか。

**Comment by OsciiArt** [comment]
thank you for seeing.
now DeepAA on web is available at here (not my work). https://tar-bin.github.io/DeepAAonWeb/#
can it be count as practice example?
sorry I don't understand "圧縮できる方法は見られますか。"
I may understand if you write in English.

**Comment by Edward-liang** [comment]
@OsciiArt Thank you for your reply.
Sorry that my Japanese is still at basic level, and may have caused some confusion.  : P
"圧縮できる方法は見られますか。" is used to confirm whether your application can be viewed as certain type of information compress method, or should it be viewed as art ?

**Comment by OsciiArt** [comment]
@Edward-liang Thank you for your reply.
I don't think it is useful for information compressing.
representation ability of ASCII Art is very week. It's so difficult to decode original image from ASCII art.
I think It's just a art.
